const recipes = [
    // Existing Recipes (1-6)
    {
        id: 1,
        title: "매콤 바질 파스타",
        category: "dinner",
        mood: ["adventure", "energetic"],
        time: "25분",
        calories: "450 kcal",
        image: "https://images.unsplash.com/photo-1551183053-bf91b1d743a4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "신선한 바질과 매콤한 페페론치노가 어우러진 깔끔한 파스타입니다.",
        ingredients: ["파스타면 200g", "신선한 바질 1컵", "마늘 2쪽", "페페론치노 1작은술", "올리브 오일", "소금 & 후추"],
        instructions: ["파스타면을 알덴테로 삶습니다.", "올리브 오일에 마늘과 페페론치노를 볶아 향을 냅니다.", "삶은 면과 신선한 바질을 넣고 가볍게 볶습니다.", "파마산 치즈를 뿌려 완성합니다."]
    },
    {
        id: 2,
        title: "아보카도 오픈 토스트",
        category: "breakfast",
        mood: ["healthy", "energetic"],
        time: "10분",
        calories: "320 kcal",
        image: "https://images.unsplash.com/photo-1541519572-b7e6b063d8d6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "바삭한 사워도우 위에 부드러운 아보카도와 수란을 올린 브런치입니다.",
        ingredients: ["사워도우 2쪽", "잘 익은 아보카도 1개", "달걀 2개", "레몬즙", "크러쉬드 레드페퍼", "소금"],
        instructions: ["빵을 노릇하게 구워줍니다.", "아보카도를 으깨어 레몬즙, 소금과 섞습니다.", "수란을 원하는 익기 정도로 만듭니다.", "빵 위에 아보카도와 수란을 올리고 향신료를 뿌립니다."]
    },
    {
        id: 3,
        title: "따뜻한 소고기 스튜",
        category: "dinner",
        mood: ["comfort"],
        time: "2시간",
        calories: "600 kcal",
        image: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "뿌리 채소와 함께 푹 끓여내어 깊은 맛이 나는 소고기 스튜입니다.",
        ingredients: ["소고기 500g", "당근 3개", "감자 2개", "양파 1개", "비프 스톡", "타임", "레드 와인"],
        instructions: ["냄비에 소고기를 넣어 겉면을 시어링합니다.", "손질한 채소를 넣고 볶습니다.", "육수와 와인을 넣고 2시간 동안 뭉근하게 끓입니다.", "소금, 후추로 간을 하고 빵과 함께 냅니다."]
    },
    {
        id: 4,
        title: "레인보우 퀴노아 샐러드",
        category: "lunch",
        mood: ["healthy"],
        time: "20분",
        calories: "380 kcal",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "단백질이 풍부한 퀴노아와 신선한 채소가 가득한 건강 샐러드입니다.",
        ingredients: ["퀴노아 1컵", "방울토마토", "오이", "적양파", "페타 치즈", "레몬 비네그레트"],
        instructions: ["퀴노아를 삶아 식혀둡니다.", "모든 채소를 먹기 좋은 크기로 썹니다.", "볼에 퀴노아, 채소, 치즈를 담습니다.", "드레싱을 뿌려 가볍게 버무립니다."]
    },
    {
        id: 5,
        title: "미드나잇 치즈버거",
        category: "dinner",
        mood: ["comfort", "adventure"],
        time: "30분",
        calories: "850 kcal",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "육즙 가득한 패티와 녹진한 체다 치즈, 카라멜라이징 양파의 조화.",
        ingredients: ["소고기 패티", "브리오슈 번", "체다 치즈", "양파", "양상추", "토마토", "특제 소스"],
        instructions: ["패티를 원하는 굽기로 굽습니다.", "양파를 갈색이 날 때까지 볶습니다.", "번을 살짝 굽습니다.", "준비된 재료를 차곡차곡 쌓아 완성합니다."]
    },
    {
        id: 6,
        title: "베리 스무디 보울",
        category: "breakfast",
        mood: ["healthy", "energetic"],
        time: "5분",
        calories: "280 kcal",
        image: "https://images.unsplash.com/photo-1511690078903-71dc501247fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "상큼한 베리 스무디 위에 그래놀라와 과일을 올린 가벼운 한 끼.",
        ingredients: ["냉동 믹스 베리", "바나나", "아몬드 밀크", "그래놀라", "치아씨드"],
        instructions: ["베리, 바나나, 우유를 넣고 걸쭉하게 갈아줍니다.", "볼에 담습니다.", "그래놀라와 견과류, 과일로 토핑합니다."]
    },
    // New Korean Recipes (7-26)
    {
        id: 7,
        title: "김치찌개",
        category: "dinner",
        mood: ["comfort", "adventure"],
        time: "40분",
        calories: "400 kcal",
        image: "https://images.unsplash.com/photo-1583225214464-9296e02d70c4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "잘 익은 김치와 돼지고기를 넣고 푹 끓인 한국인의 소울 푸드.",
        ingredients: ["신김치 1/4포기", "돼지고기 목살 200g", "두부 1/2모", "대파", "청양고추", "고춧가루"],
        instructions: ["돼지고기를 냄비에 볶다가 김치를 넣어 함께 볶습니다.", "물을 붓고 김치가 무를 때까지 푹 끓입니다.", "두부와 대파, 고추를 넣고 한소끔 더 끓여냅니다."]
    },
    {
        id: 8,
        title: "전주 비빔밥",
        category: "lunch",
        mood: ["healthy", "energetic"],
        time: "30분",
        calories: "550 kcal",
        image: "https://images.unsplash.com/photo-1583224964978-2257b960703d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "다채로운 나물과 고추장 양념이 어우러진 균형 잡힌 한 그릇.",
        ingredients: ["밥 1공기", "콩나물", "시금치", "당근", "고사리", "다진 소고기", "달걀", "고추장", "참기름"],
        instructions: ["각종 나물은 데쳐서 양념에 무칩니다.", "소고기는 불고기 양념으로 볶습니다.", "그릇에 밥을 담고 나물과 고기를 예쁘게 돌려 담습니다.", "가운데 달걀 프라이를 올리고 고추장을 곁들입니다."]
    },
    {
        id: 9,
        title: "소불고기",
        category: "dinner",
        mood: ["comfort"],
        time: "30분 (재우는 시간 제외)",
        calories: "480 kcal",
        image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "달콤 짭짤한 양념에 재운 소고기를 볶아낸 남녀노소 인기 메뉴.",
        ingredients: ["불고기용 소고기 600g", "양파 1개", "대파", "당근", "간장", "설탕", "다진 마늘", "참기름"],
        instructions: ["소고기에 갖은 양념을 넣어 30분 이상 재웁니다.", "달군 팬에 고기를 볶습니다.", "고기가 반쯤 익으면 채소를 넣어 같이 볶아 완성합니다."]
    },
    {
        id: 10,
        title: "잡채",
        category: "dinner",
        mood: ["comfort", "energetic"],
        time: "45분",
        calories: "350 kcal",
        image: "https://images.unsplash.com/photo-1628203874013-43c3f2277024?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "쫄깃한 당면과 다양한 채소를 볶아 버무린 잔치 음식.",
        ingredients: ["당면 200g", "시금치", "당근", "양파", "표고버섯", "소고기", "간장", "설탕", "참기름"],
        instructions: ["당면을 삶아 찬물에 헹굽니다.", "각 채소와 고기를 따로 볶습니다.", "큰 볼에 당면과 볶은 재료를 넣고 양념장에 버무립니다."]
    },
    {
        id: 11,
        title: "매콤 떡볶이",
        category: "lunch",
        mood: ["adventure", "comfort"],
        time: "20분",
        calories: "400 kcal",
        image: "https://images.unsplash.com/photo-1548154189-989204c405a0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "매콤달콤한 고추장 소스에 쫄깃한 떡과 어묵의 조화.",
        ingredients: ["떡볶이 떡 300g", "사각 어묵 2장", "대파", "고추장", "고춧가루", "설탕", "물엿"],
        instructions: ["육수에 양념장을 풀고 끓입니다.", "떡과 어묵을 넣고 중약불에서 졸입니다.", "대파를 넣고 국물이 걸쭉해질 때까지 끓입니다."]
    },
    {
        id: 12,
        title: "갈비찜",
        category: "dinner",
        mood: ["comfort"],
        time: "1시간 30분",
        calories: "700 kcal",
        image: "https://images.unsplash.com/photo-1606757388703-9d846059c36a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "부드러운 소갈비에 단짠 양념이 배어든 최고의 밥도둑.",
        ingredients: ["소갈비 1kg", "무", "당근", "표고버섯", "밤", "간장", "배즙", "다진 마늘"],
        instructions: ["갈비는 핏물을 빼고 한 번 데쳐냅니다.", "양념장과 물을 붓고 40분 이상 끓입니다.", "채소를 넣고 국물이 자작해질 때까지 졸입니다."]
    },
    {
        id: 13,
        title: "삼계탕",
        category: "dinner",
        mood: ["healthy", "energetic"],
        time: "1시간",
        calories: "650 kcal",
        image: "https://images.unsplash.com/photo-1627885233161-0b5c1902095f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "여름철 원기 회복을 위한 진한 국물의 닭 요리.",
        ingredients: ["생닭 1마리", "인삼 1뿌리", "대추", "마늘", "찹쌀", "각종 한약재"],
        instructions: ["닭 뱃속에 불린 찹쌀과 마늘, 대추를 넣습니다.", "냄비에 닭과 재료, 물을 넣고 1시간 푹 끓입니다.", "소금과 후추로 간을 하여 먹습니다."]
    },
    {
        id: 14,
        title: "된장찌개",
        category: "dinner",
        mood: ["comfort", "healthy"],
        time: "25분",
        calories: "300 kcal",
        image: "https://images.unsplash.com/photo-1545620853-2bf994c9247e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "구수한 된장 국물에 두부와 호박이 들어간 가정식 백반의 정석.",
        ingredients: ["된장 2큰술", "애호박", "두부", "양파", "버섯", "멸치 육수", "청양고추"],
        instructions: ["육수에 된장을 풉니다.", "단단한 채소부터 넣고 끓입니다.", "두부와 버섯, 고추를 넣고 한소끔 끓여냅니다."]
    },
    {
        id: 15,
        title: "김밥",
        category: "lunch",
        mood: ["energetic", "adventure"],
        time: "40분",
        calories: "450 kcal",
        image: "https://images.unsplash.com/photo-1616645308325-1e4e8c1b849c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "다양한 재료를 밥과 김으로 말아낸 간편하고 든든한 한 끼.",
        ingredients: ["김밥김", "밥", "단무지", "햄", "달걀 지단", "시금치", "당근", "참기름"],
        instructions: ["밥에 참기름과 소금으로 밑간을 합니다.", "속재료를 길게 준비하고 볶습니다.", "김 위에 밥을 펴고 재료를 올려 단단하게 맙니다."]
    },
    {
        id: 16,
        title: "순두부 찌개",
        category: "dinner",
        mood: ["comfort", "adventure"],
        time: "20분",
        calories: "350 kcal",
        image: "https://images.unsplash.com/photo-1583225214464-9296e02d70c4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "부드러운 순두부와 얼큰한 국물이 일품인 찌개.",
        ingredients: ["순두부 1봉", "바지락", "달걀 1개", "대파", "고추기름", "다진 마늘"],
        instructions: ["뚝배기에 고추기름을 두르고 파와 마늘을 볶습니다.", "해감된 바지락과 물을 넣고 끓입니다.", "순두부를 넣고 끓이다가 마지막에 달걀을 넣습니다."]
    },
    {
        id: 17,
        title: "보쌈",
        category: "dinner",
        mood: ["comfort"],
        time: "1시간",
        calories: "750 kcal",
        image: "https://images.unsplash.com/photo-1626665715974-9f75d688005b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "부드럽게 삶아낸 돼지고기를 김치와 쌈에 싸 먹는 요리.",
        ingredients: ["돼지고기 수육용(삼겹/목살) 1kg", "된장", "통마늘", "대파", "통후추", "월계수잎"],
        instructions: ["물에 향신 채소와 된장을 풀고 끓입니다.", "고기를 넣고 40분~1시간 삶습니다.", "먹기 좋은 크기로 썰어 쌈채소와 곁들입니다."]
    },
    {
        id: 18,
        title: "춘천 닭갈비",
        category: "dinner",
        mood: ["adventure", "energetic"],
        time: "40분",
        calories: "600 kcal",
        image: "https://images.unsplash.com/photo-1622557871350-ab940ce6bd8d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "매콤한 양념에 닭고기와 양배추, 고구마를 볶아 먹는 철판 요리.",
        ingredients: ["닭다리살 500g", "양배추", "고구마", "떡", "깻잎", "고추장 양념"],
        instructions: ["닭고기와 채소를 적당한 크기로 썹니다.", "팬에 기름을 두르고 재료와 양념장을 넣고 볶습니다.", "재료가 다 익으면 깻잎을 넣어 마무리합니다."]
    },
    {
        id: 19,
        title: "해물 파전",
        category: "lunch",
        mood: ["comfort"],
        time: "30분",
        calories: "450 kcal",
        image: "https://images.unsplash.com/photo-1606756857187-b64816913c7c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "비 오는 날 생각나는 오징어와 새우가 듬뿍 들어간 파전.",
        ingredients: ["쪽파 1단", "오징어", "새우", "부침가루", "달걀", "식용유"],
        instructions: ["부침 반죽을 만듭니다.", "팬에 반죽을 얇게 펴고 쪽파를 올립니다.", "해물을 올리고 달걀물을 부어 노릇하게 굽습니다."]
    },
    {
        id: 20,
        title: "자장면",
        category: "lunch",
        mood: ["comfort"],
        time: "30분",
        calories: "700 kcal",
        image: "https://images.unsplash.com/photo-1625937402868-b715767c9c0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "고소한 춘장에 돼지고기와 양파를 볶아 면에 비벼 먹는 중식 요리.",
        ingredients: ["중화면", "춘장", "돼지고기", "양파", "양배추", "설탕", "전분물"],
        instructions: ["춘장을 기름에 볶습니다.", "고기와 채소를 볶다가 춘장을 섞습니다.", "물을 붓고 끓이다 전분물로 농도를 맞춥니다.", "삶은 면 위에 소스를 붓습니다."]
    },
    {
        id: 21,
        title: "얼큰 짬뽕",
        category: "lunch",
        mood: ["adventure", "energetic"],
        time: "40분",
        calories: "600 kcal",
        image: "https://images.unsplash.com/photo-1558983273-047b1129b05c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "각종 해산물과 채소로 국물을 낸 얼큰하고 시원한 국물 요리.",
        ingredients: ["중화면", "오징어", "홍합", "새우", "배추", "양파", "고춧가루", "마늘"],
        instructions: ["파기름을 내고 고춧가루를 볶아 고추기름을 만듭니다.", "해물과 채소를 볶다가 육수를 붓고 끓입니다.", "간을 맞추고 면을 삶아 함께 냅니다."]
    },
    {
        id: 22,
        title: "사골 만두국",
        category: "breakfast",
        mood: ["comfort", "healthy"],
        time: "20분",
        calories: "450 kcal",
        image: "https://images.unsplash.com/photo-1628200424578-c54dce1f42d2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "진한 사골 육수에 왕만두를 넣어 끓인 든든한 한 그릇.",
        ingredients: ["왕만두 5개", "사골 육수", "달걀", "대파", "김가루", "소금", "후추"],
        instructions: ["사골 육수를 끓이다가 만두를 넣습니다.", "만두가 익으면 달걀물을 풀고 대파를 넣습니다.", "그릇에 담고 김가루를 뿌립니다."]
    },
    {
        id: 23,
        title: "시원한 콩국수",
        category: "lunch",
        mood: ["healthy"],
        time: "20분",
        calories: "400 kcal",
        image: "https://images.unsplash.com/photo-1552590635-27c2c2128abf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "진하게 갈아 만든 콩물에 국수를 말아 먹는 여름 별미.",
        ingredients: ["소면", "콩물 (또는 두부+두유)", "오이", "방울토마토", "검은깨", "소금"],
        instructions: ["소면을 삶아 찬물에 헹굽니다.", "그릇에 면을 담고 차가운 콩물을 붓습니다.", "오이채와 토마토를 고명으로 올립니다."]
    },
    {
        id: 24,
        title: "설렁탕",
        category: "breakfast",
        mood: ["healthy", "comfort"],
        time: "5시간 이상",
        calories: "400 kcal",
        image: "https://images.unsplash.com/photo-1628200424683-9b93a2a4b8b6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "소뼈를 오랫동안 고아 만든 뽀얗고 담백한 보양식.",
        ingredients: ["사골 국물", "양지머리 수육", "소면", "대파", "소금", "후추"],
        instructions: ["그릇에 삶은 소면과 밥, 수육을 담습니다.", "뜨거운 사골 국물을 붓습니다 (토렴).", "송송 썬 대파를 듬뿍 얹어 냅니다."]
    },
    {
        id: 25,
        title: "감자탕",
        category: "dinner",
        mood: ["comfort", "adventure"],
        time: "2시간",
        calories: "700 kcal",
        image: "https://images.unsplash.com/photo-1549460592-23267d337d1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "돼지 등뼈와 우거지, 감자를 넣고 들깨가루로 맛을 낸 진한 탕.",
        ingredients: ["돼지 등뼈 1kg", "감자", "우거지", "깻잎", "들깨가루", "된장", "고춧가루"],
        instructions: ["핏물을 뺀 등뼈를 한 번 삶아냅니다.", "양념장과 우거지를 넣고 푹 끓입니다.", "감자를 넣고 익을 때까지 끓이다가 깻잎과 들깨가루를 넣습니다."]
    },
    {
        id: 26,
        title: "호박죽",
        category: "breakfast",
        mood: ["healthy", "comfort"],
        time: "30분",
        calories: "250 kcal",
        image: "https://images.unsplash.com/photo-1609121703648-5c4aa30cb703?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "늙은 호박과 찹쌀을 갈아 쑨 달콤하고 부드러운 죽.",
        ingredients: ["늙은 호박", "찹쌀가루", "설탕", "소금", "팥 (선택사항)"],
        instructions: ["호박은 껍질을 벗겨 삶은 뒤 으깹니다.", "으깬 호박에 물을 붓고 끓이다 찹쌀물로 농도를 맞춥니다.", "설탕과 소금으로 간을 합니다."]
    },
    {
        id: 27,
        title: "안동 찜닭",
        category: "dinner",
        mood: ["adventure", "comfort"],
        time: "50분",
        calories: "650 kcal",
        image: "https://images.unsplash.com/photo-1626081363262-65b066a5a413?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "짭짤하고 달콤한 간장 소스에 닭고기, 채소, 당면을 함께 졸여낸 요리.",
        ingredients: ["닭 1마리", "감자", "당근", "건고추", "당면", "간장", "설탕", "다진 마늘"],
        instructions: ["닭을 한 번 데쳐 불순물을 제거합니다.", "물과 양념장, 닭, 채소를 넣고 끓입니다.", "닭이 익으면 불린 당면을 넣고 국물이 자작해질 때까지 졸입니다."]
    },
    {
        id: 28,
        title: "육회",
        category: "dinner",
        mood: ["adventure", "energetic"],
        time: "15분",
        calories: "350 kcal",
        image: "https://images.unsplash.com/photo-1515933692209-a9c6b6d156b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "신선한 소고기 우둔살을 얇게 채 썰어 배와 함께 양념에 무쳐 먹는 음식.",
        ingredients: ["소고기 우둔살 300g", "배 1/2개", "달걀 노른자", "간장", "설탕", "참기름", "다진 마늘"],
        instructions: ["소고기는 핏물을 제거하고 얇게 채 썹니다.", "배도 같은 길이로 채 썹니다.", "양념장 재료를 섞어 소고기와 가볍게 버무립니다.", "배와 함께 접시에 담고 달걀 노른자를 올립니다."]
    },
    {
        id: 29,
        title: "부대찌개",
        category: "dinner",
        mood: ["comfort", "adventure"],
        time: "30분",
        calories: "550 kcal",
        image: "https://images.unsplash.com/photo-1604503468724-38c641c8c122?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        description: "김치와 함께 햄, 소시지, 라면 등을 넣고 얼큰하게 끓인 퓨전 찌개.",
        ingredients: ["햄", "소시지", "김치", "두부", "베이크드 빈스", "라면사리", "치즈", "고추장 양념"],
        instructions: ["전골 냄비에 재료를 보기 좋게 돌려 담습니다.", "양념장과 육수를 넣고 끓입니다.", "재료가 익으면 라면사리와 치즈를 넣고 한소끔 더 끓여 완성합니다."]
    }
];
