name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 push될 때마다 워크플로우를 실행합니다.

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # 현재 디렉토리의 모든 파일을 업로드합니다.
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2